services:
  mysql-server-1:
    image: mysql/mysql-server:8.0
    container_name: mysql-server-1
    hostname: mysql-server-1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command:
      - --server-id=1
      - --binlog-format=ROW
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --log-bin=mysql-bin-1.log
      - --log-slave-updates=ON
      - --master-info-repository=TABLE
      - --relay-log-info-repository=TABLE
      - --transaction-write-set-extraction=XXHASH64
      - --user=mysql
      - --skip-host-cache
      - --skip-name-resolve
    ports:
      - "3301:3306"
    volumes:
      - ./docker-data/mysql_data_1:/var/lib/mysql
    restart: always
    networks:
      - mysql-cluster
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql-server-2:
    image: mysql/mysql-server:8.0
    container_name: mysql-server-2
    hostname: mysql-server-2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command:
      - --server-id=2
      - --binlog-format=ROW
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --log-bin=mysql-bin-2.log
      - --log-slave-updates=ON
      - --master-info-repository=TABLE
      - --relay-log-info-repository=TABLE
      - --transaction-write-set-extraction=XXHASH64
      - --user=mysql
      - --skip-host-cache
      - --skip-name-resolve
    ports:
      - "3302:3306"
    volumes:
      - ./docker-data/mysql_data_2:/var/lib/mysql
    restart: always
    networks:
      - mysql-cluster
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql-server-3:
    image: mysql/mysql-server:8.0
    container_name: mysql-server-3
    hostname: mysql-server-3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command:
      - --server-id=3
      - --binlog-format=ROW
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --log-bin=mysql-bin-3.log
      - --log-slave-updates=ON
      - --master-info-repository=TABLE
      - --relay-log-info-repository=TABLE
      - --transaction-write-set-extraction=XXHASH64
      - --user=mysql
      - --skip-host-cache
      - --skip-name-resolve
    ports:
      - "3303:3306"
    volumes:
      - ./docker-data/mysql_data_3:/var/lib/mysql
    restart: always
    networks:
      - mysql-cluster
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql-server-pma
    depends_on:
      - mysql-server-1  # Or any of the MySQL servers
    environment:
      PMA_HOST: mysql-server-1  # Hostname of your MySQL server
      PMA_PORT: "3306"        # Port of your MySQL server
      PMA_ARBITRARY: 1

    links:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3

    ports:
      - 8089:80
    networks:
      - mysql-cluster

  mysql-router:
    image: mysql/mysql-router:8.0
    container_name: mysql-router
    hostname: mysql-router
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql-server-1
      - MYSQL_PORT=3306
      - MYSQL_CREATE_ROUTER_USER=0
      - MYSQL_ROUTER_BOOTSTRAP_MEMORY=true
    ports:
      - "6446:6446"
      - "6447:6447"
      - "64460:64460"
      - "64470:64470"
    networks:
      - mysql-cluster
    restart: on-failure
    command:
      - mysqlrouter
    volumes:
      - ./docker-data/router:/var/lib/mysqlrouter


networks:
  mysql-cluster:
    driver: bridge

volumes:
  mysql_data_1:
  mysql_data_2:
  mysql_data_3:
